In [31]:
import numpy as np

In [32]:
import pandas as pd

In [33]:
population = pd.DataFrame(np.arange(10)+1)

In [34]:
population

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [35]:
population.mean()

0    5.5
dtype: float64

In [36]:
population.std()

0    3.02765
dtype: float64

In [37]:
# With random_state we fix the random generator (sampling without replacement)
s1 = population.sample(n=3, random_state=1)
s1

    0
2   3
9  10
6   7

In [38]:
s1.mean()

0    6.666667
dtype: float64

In [39]:
s1.std()

0    3.511885
dtype: float64

In [40]:
s2 = population.sample(n=3, random_state=2)

In [41]:
s2

   0
4  5
1  2
5  6

In [42]:
s2.mean()

0    4.333333
dtype: float64

In [43]:
s2.std()

0    2.081666
dtype: float64

In [44]:
# With random_state we fix the random generator (sampling with replacement)
s3 = population.sample(frac=0.5, replace=True, random_state=1)

In [45]:
s3

    0
5   6
8   9
9  10
5   6
0   1

In [46]:
s3.mean()

0    6.4
dtype: float64

In [47]:
s3.std()

0    3.507136
dtype: float64

In [48]:
s4 = population.sample(frac=0.5, replace=True, random_state=2)

In [49]:
s4

   0
8  9
8  9
6  7
2  3
8  9

In [50]:
s4.mean()

0    7.4
dtype: float64

In [51]:
s4.std()

0    2.607681
dtype: float64